modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="fc"
version="0.1.0"
displayName="Food Collection"
credits="Created at 11/15/2022"
displayURL="https://www.curseforge.com/minecraft/mc-mods/food-collection"
logoFile="logo.png"
authors="RakaGIT /  industrymine"
description='''
More food! With many Types, Colors, Variations, Shapes, and
'''

[[dependencies.fc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




